### ISSUE TITLE
Comprehensive requirements: Version 3

### ISSUE THREAD

**Issue by philhagen** [sans-sroc/integrity#37]
Some new developments have opened up GREAT opportunities to continue all of the improvements done so far!  This will result in more streamlined processes for authors and everyone else in the mix.

1. Single output filename, in YAML format, placed in root directory
2. Filename can be universal.  for example, `sans-integrity.yml`.
3. Everything we need to track goes into the YAML file.  A suggestion/example is below, but ABSOLUTELY subject to discussion and modification before we declare anything final.
```
### SANS Integrity Validation File
iso_name: '123.21.1A'
date_created: '2021-05-13T15:12:15+00:00'
integrity_version: 2.0.1
created_by: 'phil'
root_path: '/path/to/root/dir'
hash_algorithm: 'sha256'

contents:
- split_files:
  - '/get_first/Windows_VM.7z': 'b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c'
- main_files:
  - '/readme.txt': 'b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c'
  - '/lab_data/testfile1.pdf': 'b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c'
  - '/vmware_images/something.7z': b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c'
```
4. The `iso_name` field (or whatever we will call it) must match the following regex: `[0-9]{3}\.[0-9]{2}\.[0-9][A-Z]?`.  (Dots between, 3/2/1 digit sets required, uppercase alpha suffix optional.)  The Integrity tool must exit with an error if the user specifies a volume name that does not match.
5. During checksum file **creation**, a list of detritus files to SKIP will be needed and should be built into the integrity binary (e.g. binary does not require any external config files).  For example: `.DS_Store` (in any directory), `desktop.ini` (in any directory), `.System Volume Information` (in the root directory).  Probably more - and we can add those as we encounter them.  (Note that these files MUST NOT be skipped on **validation** runs.
6. Running a validation will assume you're running from the root of the iso media or USB drive.  An optional root directory can be included as well.
5. During **validation** runs, the Integrity tool must determine if there is a `contents:split_files` entry.  If so, determine if there is a `/get_first/` directory present.  If both are true, perform a full validation of all contents.  (This would occur when validating a physical USB device, for example.)  If there is a `contents:split_files` entry and there is **NOT** a `/get_first/` directory, the Integrity tool assumes it is validating a partial ISO and skips the validation of the files in the `/get_first/` directory.
6. During **validation** runs, the Integrity tool will NOT skip any files.  Every file in the specified root directory will be processed, including detritus files.  Integrity must fail validation if these files are present, just as any other newly-added file.
7. During **validation** runs, the Integrity tool must ignore any files in the root directory with filenames that start with the checksum file.  This will allow GPG signing the checksum files, which will be recommended but not required.  For example, a filename of `sans-integrity.yml.gpg` will be skipped even though that file is not listed in the `contents:main_files` list.
8. (ADDED after initial issue creation) During checksum file **creation**, if the `/get_first/` directory is empty, the Integrity tool will exit with an error indicating this is not supported and directing the user to remove the empty directory before re-running the tool.

That should cover all of the known bases right now, but we're going to have more discussions around this of course.  Whether this becomes 2.5 or 3.0 is up to you all, but this will all result in a greatly streamlined process for everyone!

**Comment by philhagen** [comment]
Also, this issue will likely obsolete several others, which is fine

**Comment by ekristen** [comment]
Thanks @philhagen I think this will become 3.0 because it'll incorporate a number of breaking changes. I've already started working on some of this. 

- 1-3, check and yes ;)
- 4, easy
- 5, agreed, I already stubbed out an `--ignore switch` with a set of defaults so it can be modified by the user at create time.
- 6 yes, agrred
- 7-8 yes, already have these changes in a local branch I was working on last night while watching TV :)
- 9 easy to support as well

As it stands right now the file format looks something like this and it's mainly to align with golang struct import/export.

```yaml
files:
  - file: get_first/Windows_VM.7z
     hash: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
  - file: readme.txt
     hash: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
```

The file path assumes relative to the specified directory when the tool is run, with that in mind, I'm not sure `root_path` in the YAML makes sense since it's unlikely it'll always be the same path.

The tool has a `-d` option that defaults to `.`, and assumes all files are relative to the `-d` option, this can obviously be changed, but I think it makes sense. 

For the split files vs main files, I like the distinction, perhaps we can augment the struct to include a type, or we can keep them separately, let me play with this a little in the internal mechanisms to see what works best and I'll provide feedback. 

Something like this maybe

```yaml
files:
  - file: get_first/Windows_VM.7z
     hash: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
     split: true
  - file: readme.txt
     hash: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
     split: false
```

or 


```yaml
contents:
  split:
  - file: get_first/Windows_VM.7z
     hash: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
  main:
  - file: readme.txt
     hash: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
```
