### ISSUE TITLE
Integrity verification of files once moved

### ISSUE THREAD

**Issue by MarkBaggett** [sans-sroc/integrity#48]
The purpose of the get_first folder is to allow authors to specify content that will be pulled from the main package and processed separately.  The get_first folder will be copied to various production servers separate from the main package where students will download it.

After the copy process has occurred we need to use integrity to verify the contents of the folder matches the original content uploaded by the author.

At the moment media_processor will copy the get_first folder to a "downloads" location where it will then be transfered to another server for student download.   I place a copy of "sans-integrity.yml" into the downloads folder so it can be used to validate the contents of "get_first" on the final resting place.

When I attempt to validate the files it is unable to resolve the new directory structure.

**Comment by ekristen** [comment]
Per @philhagen any missing or added file is an error period. We skip get_first (ie downloads) if they aren't present.

Maybe we rename get_first to downloads to keep naming conventions consistent across the boards?

I'm a little confused by the output, it seems that you copied no file that integrity had created a validation for previously? Looks like a file was added and a bunch missing? I know you said you can ignore the missing.

FYI, the output-format and output flags can help you write json to a file or stdout of the status of all the files.

**Comment by MarkBaggett** [comment]
Correct.  Copied the original "sans-integrity.yml" file and placed it into the folder with the downloads.  As a result of the relocation the paths to the files in the yml no longer match the files in the directory so integrity doesn't find the files where they are needed.  However, the hashes should still match.  

Integrity has what it needs in the yml.   Those files listed in the split section:

```
files:
  split:
  - file: get_first/SEC560 Slingshot Linux (F06).ova
    hash: c0ef1c8d11d0694b09f13cbd2da67db781b682fa4141d28b9892e65bc67f44ad
  core:
  - file: Cheat_Sheets/IPv6_PRG.pdf
    hash: a80be92bd53e2151d08c9576c505bccce4aa7ce94aadb5a047a7a21ad7d85a80
```
need to be confirmed without regard to path since split moves.
